development:
  adapter: postgresql
  database: growstuff_dev
  host: localhost
  user: psql_user
  password: 123456

test:
  adapter: postgresql
  database: growstuff_test
  host: localhost
  user: psql_user
  password: 123456

production:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword

staging:
  adapter: postgresql
  database: growstuff_prod
  pool: 5
  timeout: 5000
  username: growstuff
  host: localhost
  password: thisisnottherealpassword
